import Noticia from "@/types/Noticia/Noticia";

const Data: Array<Noticia> = [
    { id: 1, titulo: "Notícia 1", data: new Date('2024-10-01'), conteudo: "Conteúdo da notícia 1.", imagem: "https://robohash.org/1", Categorias: ["Categoria A"], Comentarios: [{ nome: "Daniel", texto: "oi" }] },
    { id: 2, titulo: "Notícia 2", data: new Date('2024-09-30'), conteudo: "Conteúdo da notícia 2.", imagem: "https://robohash.org/2", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 3, titulo: "Notícia 3", data: new Date('2024-09-29'), conteudo: "Conteúdo da notícia 3.", imagem: "https://robohash.org/3", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 4, titulo: "Notícia 4", data: new Date('2024-09-28'), conteudo: "Conteúdo da notícia 4.", imagem: "https://robohash.org/4", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 5, titulo: "Notícia 5", data: new Date('2024-09-27'), conteudo: "Conteúdo da notícia 5.", imagem: "https://robohash.org/5", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 6, titulo: "Notícia 6", data: new Date('2024-09-26'), conteudo: "Conteúdo da notícia 6.", imagem: "https://robohash.org/6", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 7, titulo: "Notícia 7", data: new Date('2024-09-25'), conteudo: "Conteúdo da notícia 7.", imagem: "https://robohash.org/7", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 8, titulo: "Notícia 8", data: new Date('2024-09-24'), conteudo: "Conteúdo da notícia 8.", imagem: "https://robohash.org/8", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 9, titulo: "Notícia 9", data: new Date('2024-09-23'), conteudo: "Conteúdo da notícia 9.", imagem: "https://robohash.org/9", Categorias: ["Categoria B"], Comentarios: [] },
    { id: 10, titulo: "Notícia 10", data: new Date('2024-09-22'), conteudo: "Conteúdo da notícia 10.", imagem: "https://robohash.org/10", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 11, titulo: "Notícia 11", data: new Date('2024-09-21'), conteudo: "Conteúdo da notícia 11.", imagem: "https://robohash.org/11", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 12, titulo: "Notícia 12", data: new Date('2024-09-20'), conteudo: "Conteúdo da notícia 12.", imagem: "https://robohash.org/12", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 13, titulo: "Notícia 13", data: new Date('2024-09-19'), conteudo: "Conteúdo da notícia 13.", imagem: "https://robohash.org/13", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 14, titulo: "Notícia 14", data: new Date('2024-09-18'), conteudo: "Conteúdo da notícia 14.", imagem: "https://robohash.org/14", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 15, titulo: "Notícia 15", data: new Date('2024-09-17'), conteudo: "Conteúdo da notícia 15.", imagem: "https://robohash.org/15", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 16, titulo: "Notícia 16", data: new Date('2024-09-16'), conteudo: "Conteúdo da notícia 16.", imagem: "https://robohash.org/16", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 17, titulo: "Notícia 17", data: new Date('2024-09-15'), conteudo: "Conteúdo da notícia 17.", imagem: "https://robohash.org/17", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 18, titulo: "Notícia 18", data: new Date('2024-09-14'), conteudo: "Conteúdo da notícia 18.", imagem: "https://robohash.org/18", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 19, titulo: "Notícia 19", data: new Date('2024-09-13'), conteudo: "Conteúdo da notícia 19.", imagem: "https://robohash.org/19", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 20, titulo: "Notícia 20", data: new Date('2024-09-12'), conteudo: "Conteúdo da notícia 20.", imagem: "https://robohash.org/20", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 21, titulo: "Notícia 21", data: new Date('2024-09-11'), conteudo: "Conteúdo da notícia 21.", imagem: "https://robohash.org/21", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 22, titulo: "Notícia 22", data: new Date('2024-09-10'), conteudo: "Conteúdo da notícia 22.", imagem: "https://robohash.org/22", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 23, titulo: "Notícia 23", data: new Date('2024-09-09'), conteudo: "Conteúdo da notícia 23.", imagem: "https://robohash.org/23", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 24, titulo: "Notícia 24", data: new Date('2024-09-08'), conteudo: "Conteúdo da notícia 24.", imagem: "https://robohash.org/24", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 25, titulo: "Notícia 25", data: new Date('2024-09-07'), conteudo: "Conteúdo da notícia 25.", imagem: "https://robohash.org/25", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 26, titulo: "Notícia 26", data: new Date('2024-09-06'), conteudo: "Conteúdo da notícia 26.", imagem: "https://robohash.org/26", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 27, titulo: "Notícia 27", data: new Date('2024-09-05'), conteudo: "Conteúdo da notícia 27.", imagem: "https://robohash.org/27", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 28, titulo: "Notícia 28", data: new Date('2024-09-04'), conteudo: "Conteúdo da notícia 28.", imagem: "https://robohash.org/28", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 29, titulo: "Notícia 29", data: new Date('2024-09-03'), conteudo: "Conteúdo da notícia 29.", imagem: "https://robohash.org/29", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 30, titulo: "Notícia 30", data: new Date('2024-09-02'), conteudo: "Conteúdo da notícia 30.", imagem: "https://robohash.org/30", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 31, titulo: "Notícia 31", data: new Date('2024-09-01'), conteudo: "Conteúdo da notícia 31.", imagem: "https://robohash.org/31", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 32, titulo: "Notícia 32", data: new Date('2024-08-31'), conteudo: "Conteúdo da notícia 32.", imagem: "https://robohash.org/32", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 33, titulo: "Notícia 33", data: new Date('2024-08-30'), conteudo: "Conteúdo da notícia 33.", imagem: "https://robohash.org/33", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 34, titulo: "Notícia 34", data: new Date('2024-08-29'), conteudo: "Conteúdo da notícia 34.", imagem: "https://robohash.org/34", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 35, titulo: "Notícia 35", data: new Date('2024-08-28'), conteudo: "Conteúdo da notícia 35.", imagem: "https://robohash.org/35", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 36, titulo: "Notícia 36", data: new Date('2024-08-27'), conteudo: "Conteúdo da notícia 36.", imagem: "https://robohash.org/36", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 37, titulo: "Notícia 37", data: new Date('2024-08-26'), conteudo: "Conteúdo da notícia 37.", imagem: "https://robohash.org/37", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 38, titulo: "Notícia 38", data: new Date('2024-08-25'), conteudo: "Conteúdo da notícia 38.", imagem: "https://robohash.org/38", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 39, titulo: "Notícia 39", data: new Date('2024-08-24'), conteudo: "Conteúdo da notícia 39.", imagem: "https://robohash.org/39", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 40, titulo: "Notícia 40", data: new Date('2024-08-23'), conteudo: "Conteúdo da notícia 40.", imagem: "https://robohash.org/40", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 41, titulo: "Notícia 41", data: new Date('2024-08-22'), conteudo: "Conteúdo da notícia 41.", imagem: "https://robohash.org/41", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 42, titulo: "Notícia 42", data: new Date('2024-08-21'), conteudo: "Conteúdo da notícia 42.", imagem: "https://robohash.org/42", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 43, titulo: "Notícia 43", data: new Date('2024-08-20'), conteudo: "Conteúdo da notícia 43.", imagem: "https://robohash.org/43", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 44, titulo: "Notícia 44", data: new Date('2024-08-19'), conteudo: "Conteúdo da notícia 44.", imagem: "https://robohash.org/44", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 45, titulo: "Notícia 45", data: new Date('2024-08-18'), conteudo: "Conteúdo da notícia 45.", imagem: "https://robohash.org/45", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 46, titulo: "Notícia 46", data: new Date('2024-08-17'), conteudo: "Conteúdo da notícia 46.", imagem: "https://robohash.org/46", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 47, titulo: "Notícia 47", data: new Date('2024-08-16'), conteudo: "Conteúdo da notícia 47.", imagem: "https://robohash.org/47", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 48, titulo: "Notícia 48", data: new Date('2024-08-15'), conteudo: "Conteúdo da notícia 48.", imagem: "https://robohash.org/48", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 49, titulo: "Notícia 49", data: new Date('2024-08-14'), conteudo: "Conteúdo da notícia 49.", imagem: "https://robohash.org/49", Categorias: ["Categoria A"], Comentarios: [] },
    { id: 50, titulo: "Notícia 50", data: new Date('2024-08-13'), conteudo: "Conteúdo da notícia 50.", imagem: "https://robohash.org/50", Categorias: ["Categoria A"], Comentarios: [] }
];

export default Data;
